// Shared types between client and server for the AI audit flow.

export type PainCategory = {
  department: string;
  symptom: string; // names the wound, NOT the bandage
};

// Cost model is computed deterministically server-side from enrichment data
// (NOT generated by the LLM). Numbers are defensible — see src/lib/cost-model.ts.
export type CostModel = {
  employees: number;
  employee_source: "exact" | "bucket-midpoint" | "default";
  industry_label: string; // human-readable industry name used for math
  addressable_roles: number;
  weekly_hours_reclaimable: number;
  annual_hours_reclaimable: number;
  fully_loaded_cost_per_role: number; // USD/year
  annual_value_at_risk: number; // USD/year
  five_year_cost_of_inaction: number; // USD over 5 years (with compounding)
  // teaser hour estimates per pain category (parallel array to pain_categories)
  pain_hours_per_year: number[];
};

export type AuditReport = {
  company_name: string;
  industry: string;
  size_estimate: string;
  autonomous_workforce_score: number; // 0–100
  score_rationale: string;
  executive_summary: string;
  pain_categories: PainCategory[];
  cost_model: CostModel;
};

export type GenerateAuditResponse =
  | {
      ok: true;
      lead_id: string;
      website: string;
      email: string;
      audit: AuditReport;
      email_sent: boolean;
    }
  | {
      ok: false;
      error: string;
    };
