/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowaiRouteImport } from './routes/workflowai'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OpportunityRouteImport } from './routes/opportunity'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as PreviewExecutiveAuditRouteImport } from './routes/preview.executive-audit'
import { Route as PreviewEmployeeAnalysisRouteImport } from './routes/preview.employee-analysis'
import { Route as PreviewAgentBuilderRouteImport } from './routes/preview.agent-builder'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding.step-4'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding.step-3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding.step-2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding.step-1'
import { Route as AuthedSkillModuleRouteImport } from './routes/_authed/skill-module'
import { Route as AuthedEmployeeRouteImport } from './routes/_authed/employee'
import { Route as AuthedAssessmentRouteImport } from './routes/_authed/assessment'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/_admin/dashboard'
import { Route as AuthedAdminAdminGovernanceRouteImport } from './routes/_authed/_admin/admin.governance'
import { Route as AuthedAdminAdminEmployeesRouteImport } from './routes/_authed/_admin/admin.employees'

const WorkflowaiRoute = WorkflowaiRouteImport.update({
  id: '/workflowai',
  path: '/workflowai',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityRoute = OpportunityRouteImport.update({
  id: '/opportunity',
  path: '/opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const PreviewExecutiveAuditRoute = PreviewExecutiveAuditRouteImport.update({
  id: '/preview/executive-audit',
  path: '/preview/executive-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewEmployeeAnalysisRoute = PreviewEmployeeAnalysisRouteImport.update({
  id: '/preview/employee-analysis',
  path: '/preview/employee-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewAgentBuilderRoute = PreviewAgentBuilderRouteImport.update({
  id: '/preview/agent-builder',
  path: '/preview/agent-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/step-4',
  path: '/step-4',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthedSkillModuleRoute = AuthedSkillModuleRouteImport.update({
  id: '/skill-module',
  path: '/skill-module',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeeRoute = AuthedEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssessmentRoute = AuthedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminAdminGovernanceRoute =
  AuthedAdminAdminGovernanceRouteImport.update({
    id: '/admin/governance',
    path: '/admin/governance',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminEmployeesRoute =
  AuthedAdminAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/opportunity': typeof OpportunityRoute
  '/signup': typeof SignupRoute
  '/workflowai': typeof WorkflowaiRoute
  '/assessment': typeof AuthedAssessmentRoute
  '/employee': typeof AuthedEmployeeRoute
  '/skill-module': typeof AuthedSkillModuleRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/preview/agent-builder': typeof PreviewAgentBuilderRoute
  '/preview/employee-analysis': typeof PreviewEmployeeAnalysisRoute
  '/preview/executive-audit': typeof PreviewExecutiveAuditRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/employees': typeof AuthedAdminAdminEmployeesRoute
  '/admin/governance': typeof AuthedAdminAdminGovernanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/opportunity': typeof OpportunityRoute
  '/signup': typeof SignupRoute
  '/workflowai': typeof WorkflowaiRoute
  '/assessment': typeof AuthedAssessmentRoute
  '/employee': typeof AuthedEmployeeRoute
  '/skill-module': typeof AuthedSkillModuleRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/preview/agent-builder': typeof PreviewAgentBuilderRoute
  '/preview/employee-analysis': typeof PreviewEmployeeAnalysisRoute
  '/preview/executive-audit': typeof PreviewExecutiveAuditRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/employees': typeof AuthedAdminAdminEmployeesRoute
  '/admin/governance': typeof AuthedAdminAdminGovernanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/opportunity': typeof OpportunityRoute
  '/signup': typeof SignupRoute
  '/workflowai': typeof WorkflowaiRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/assessment': typeof AuthedAssessmentRoute
  '/_authed/employee': typeof AuthedEmployeeRoute
  '/_authed/skill-module': typeof AuthedSkillModuleRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/preview/agent-builder': typeof PreviewAgentBuilderRoute
  '/preview/employee-analysis': typeof PreviewEmployeeAnalysisRoute
  '/preview/executive-audit': typeof PreviewExecutiveAuditRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_authed/_admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/_admin/admin/employees': typeof AuthedAdminAdminEmployeesRoute
  '/_authed/_admin/admin/governance': typeof AuthedAdminAdminGovernanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/faq'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/opportunity'
    | '/signup'
    | '/workflowai'
    | '/assessment'
    | '/employee'
    | '/skill-module'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/preview/agent-builder'
    | '/preview/employee-analysis'
    | '/preview/executive-audit'
    | '/onboarding/'
    | '/dashboard'
    | '/admin/employees'
    | '/admin/governance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/faq'
    | '/join'
    | '/login'
    | '/opportunity'
    | '/signup'
    | '/workflowai'
    | '/assessment'
    | '/employee'
    | '/skill-module'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/preview/agent-builder'
    | '/preview/employee-analysis'
    | '/preview/executive-audit'
    | '/onboarding'
    | '/dashboard'
    | '/admin/employees'
    | '/admin/governance'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/demo'
    | '/faq'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/opportunity'
    | '/signup'
    | '/workflowai'
    | '/_authed/_admin'
    | '/_authed/assessment'
    | '/_authed/employee'
    | '/_authed/skill-module'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/preview/agent-builder'
    | '/preview/employee-analysis'
    | '/preview/executive-audit'
    | '/onboarding/'
    | '/_authed/_admin/dashboard'
    | '/_authed/_admin/admin/employees'
    | '/_authed/_admin/admin/governance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  OpportunityRoute: typeof OpportunityRoute
  SignupRoute: typeof SignupRoute
  WorkflowaiRoute: typeof WorkflowaiRoute
  PreviewAgentBuilderRoute: typeof PreviewAgentBuilderRoute
  PreviewEmployeeAnalysisRoute: typeof PreviewEmployeeAnalysisRoute
  PreviewExecutiveAuditRoute: typeof PreviewExecutiveAuditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflowai': {
      id: '/workflowai'
      path: '/workflowai'
      fullPath: '/workflowai'
      preLoaderRoute: typeof WorkflowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity': {
      id: '/opportunity'
      path: '/opportunity'
      fullPath: '/opportunity'
      preLoaderRoute: typeof OpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/preview/executive-audit': {
      id: '/preview/executive-audit'
      path: '/preview/executive-audit'
      fullPath: '/preview/executive-audit'
      preLoaderRoute: typeof PreviewExecutiveAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/employee-analysis': {
      id: '/preview/employee-analysis'
      path: '/preview/employee-analysis'
      fullPath: '/preview/employee-analysis'
      preLoaderRoute: typeof PreviewEmployeeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/agent-builder': {
      id: '/preview/agent-builder'
      path: '/preview/agent-builder'
      fullPath: '/preview/agent-builder'
      preLoaderRoute: typeof PreviewAgentBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-4': {
      id: '/onboarding/step-4'
      path: '/step-4'
      fullPath: '/onboarding/step-4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-3': {
      id: '/onboarding/step-3'
      path: '/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-2': {
      id: '/onboarding/step-2'
      path: '/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-1': {
      id: '/onboarding/step-1'
      path: '/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authed/skill-module': {
      id: '/_authed/skill-module'
      path: '/skill-module'
      fullPath: '/skill-module'
      preLoaderRoute: typeof AuthedSkillModuleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employee': {
      id: '/_authed/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthedEmployeeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assessment': {
      id: '/_authed/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthedAssessmentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin/dashboard': {
      id: '/_authed/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/governance': {
      id: '/_authed/_admin/admin/governance'
      path: '/admin/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AuthedAdminAdminGovernanceRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/employees': {
      id: '/_authed/_admin/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthedAdminAdminEmployeesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedAdminAdminEmployeesRoute: typeof AuthedAdminAdminEmployeesRoute
  AuthedAdminAdminGovernanceRoute: typeof AuthedAdminAdminGovernanceRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedAdminAdminEmployeesRoute: AuthedAdminAdminEmployeesRoute,
  AuthedAdminAdminGovernanceRoute: AuthedAdminAdminGovernanceRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedAssessmentRoute: typeof AuthedAssessmentRoute
  AuthedEmployeeRoute: typeof AuthedEmployeeRoute
  AuthedSkillModuleRoute: typeof AuthedSkillModuleRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedAssessmentRoute: AuthedAssessmentRoute,
  AuthedEmployeeRoute: AuthedEmployeeRoute,
  AuthedSkillModuleRoute: AuthedSkillModuleRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  OpportunityRoute: OpportunityRoute,
  SignupRoute: SignupRoute,
  WorkflowaiRoute: WorkflowaiRoute,
  PreviewAgentBuilderRoute: PreviewAgentBuilderRoute,
  PreviewEmployeeAnalysisRoute: PreviewEmployeeAnalysisRoute,
  PreviewExecutiveAuditRoute: PreviewExecutiveAuditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
