/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OpportunityRouteImport } from './routes/opportunity'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSkillModuleRouteImport } from './routes/_authed/skill-module'
import { Route as AuthedEmployeeRouteImport } from './routes/_authed/employee'
import { Route as AuthedAssessmentRouteImport } from './routes/_authed/assessment'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/_admin/dashboard'
import { Route as AuthedAdminAdminGovernanceRouteImport } from './routes/_authed/_admin/admin.governance'
import { Route as AuthedAdminAdminEmployeesRouteImport } from './routes/_authed/_admin/admin.employees'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityRoute = OpportunityRouteImport.update({
  id: '/opportunity',
  path: '/opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSkillModuleRoute = AuthedSkillModuleRouteImport.update({
  id: '/skill-module',
  path: '/skill-module',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeeRoute = AuthedEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssessmentRoute = AuthedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminAdminGovernanceRoute =
  AuthedAdminAdminGovernanceRouteImport.update({
    id: '/admin/governance',
    path: '/admin/governance',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminEmployeesRoute =
  AuthedAdminAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/opportunity': typeof OpportunityRoute
  '/signup': typeof SignupRoute
  '/assessment': typeof AuthedAssessmentRoute
  '/employee': typeof AuthedEmployeeRoute
  '/skill-module': typeof AuthedSkillModuleRoute
  '/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/employees': typeof AuthedAdminAdminEmployeesRoute
  '/admin/governance': typeof AuthedAdminAdminGovernanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/opportunity': typeof OpportunityRoute
  '/signup': typeof SignupRoute
  '/assessment': typeof AuthedAssessmentRoute
  '/employee': typeof AuthedEmployeeRoute
  '/skill-module': typeof AuthedSkillModuleRoute
  '/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/employees': typeof AuthedAdminAdminEmployeesRoute
  '/admin/governance': typeof AuthedAdminAdminGovernanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/demo': typeof DemoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/opportunity': typeof OpportunityRoute
  '/signup': typeof SignupRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/assessment': typeof AuthedAssessmentRoute
  '/_authed/employee': typeof AuthedEmployeeRoute
  '/_authed/skill-module': typeof AuthedSkillModuleRoute
  '/_authed/_admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/_admin/admin/employees': typeof AuthedAdminAdminEmployeesRoute
  '/_authed/_admin/admin/governance': typeof AuthedAdminAdminGovernanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/join'
    | '/login'
    | '/opportunity'
    | '/signup'
    | '/assessment'
    | '/employee'
    | '/skill-module'
    | '/dashboard'
    | '/admin/employees'
    | '/admin/governance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/join'
    | '/login'
    | '/opportunity'
    | '/signup'
    | '/assessment'
    | '/employee'
    | '/skill-module'
    | '/dashboard'
    | '/admin/employees'
    | '/admin/governance'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/demo'
    | '/join'
    | '/login'
    | '/opportunity'
    | '/signup'
    | '/_authed/_admin'
    | '/_authed/assessment'
    | '/_authed/employee'
    | '/_authed/skill-module'
    | '/_authed/_admin/dashboard'
    | '/_authed/_admin/admin/employees'
    | '/_authed/_admin/admin/governance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DemoRoute: typeof DemoRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  OpportunityRoute: typeof OpportunityRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity': {
      id: '/opportunity'
      path: '/opportunity'
      fullPath: '/opportunity'
      preLoaderRoute: typeof OpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/skill-module': {
      id: '/_authed/skill-module'
      path: '/skill-module'
      fullPath: '/skill-module'
      preLoaderRoute: typeof AuthedSkillModuleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employee': {
      id: '/_authed/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthedEmployeeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assessment': {
      id: '/_authed/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthedAssessmentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin/dashboard': {
      id: '/_authed/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/governance': {
      id: '/_authed/_admin/admin/governance'
      path: '/admin/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AuthedAdminAdminGovernanceRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/employees': {
      id: '/_authed/_admin/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthedAdminAdminEmployeesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedAdminAdminEmployeesRoute: typeof AuthedAdminAdminEmployeesRoute
  AuthedAdminAdminGovernanceRoute: typeof AuthedAdminAdminGovernanceRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedAdminAdminEmployeesRoute: AuthedAdminAdminEmployeesRoute,
  AuthedAdminAdminGovernanceRoute: AuthedAdminAdminGovernanceRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedAssessmentRoute: typeof AuthedAssessmentRoute
  AuthedEmployeeRoute: typeof AuthedEmployeeRoute
  AuthedSkillModuleRoute: typeof AuthedSkillModuleRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedAssessmentRoute: AuthedAssessmentRoute,
  AuthedEmployeeRoute: AuthedEmployeeRoute,
  AuthedSkillModuleRoute: AuthedSkillModuleRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DemoRoute: DemoRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  OpportunityRoute: OpportunityRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
